### PR TITLE
Add scroll to

### PR DESCRIPTION
**Pull request by IniZio**
connects oursky/bounty#2

I tried to get type of callexpression's parent to see if it's window but failed,

```js
CallExpression(node: TSESTree.CallExpression) {
    const callee = node.callee;

    const originalNode = esTreeNodeToTSNodeMap.get(node.parent!);
    const checker = program.getTypeChecker();

    const type = checker.getTypeAtLocation(originalNode);
    const typeString = checker.typeToString(type);

    console.log('=== type string? ', typeString);
    if (util.isIdentifier(callee, 'scrollTo')) {
        report(callee);
    }
},
``` 

apart from that, the rule can distinguish cases like

```js
scrollTo();

window.scrollTo();

const { scrollTo } = window; const SCROLLTO = scrollTo; SCROLLTO();
```

### CODE REVIEW

**Comment by louischan-oursky** [comment]
I have restructured the repo to a eslint plugin.

To add a new rule,

1. Add the rule file in `src/rules`
2. Export the rule in `src/rules/index.ts`
3. Edit `src/configs/oursky.ts` to enable the rule

To test the new rule,

1. Add a sample file in `test/src`
2. Edit `test/test.js` to include the sample file to test.

**Comment by IniZio** [comment]
@louischan-oursky I think you can't really use snapshot testing for eslint though? because the messages use absolute path. Instead maybe can do it like https://github.com/xojs/eslint-config-xo-typescript/blob/master/test/test.js?

**Comment by louischan-oursky** [comment]
The problem is not about snapshot testing but the actual output is including the absolute path. Let me investigate whether tell eslint to output a relative path instead.

**Comment by louischan-oursky** [comment]
The absolute path problem was fixed in https://github.com/oursky/eslint-oursky/commit/7641fd6a0be8af90625aceebbdb031c550eccd0e

**Comment by rickmak** [comment]
@IniZio got time to update it?

**Pull request closed without merging**
